//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_View
    {
        public string AdvertisementID { get; set; }
        public Nullable<int> CandidateInfoID { get; set; }
        public string MinimumRank { get; set; }
        public string MaximumRank { get; set; }
        public string Designator { get; set; }
        public string AQD { get; set; }
        public string NOBC { get; set; }
        public string Rating { get; set; }
        public string NEC { get; set; }
        public string Qualifications { get; set; }
        public string SecurityClearanceTypeID { get; set; }
        public Nullable<short> SecurityClearanceRequiredID { get; set; }
        public string Gender { get; set; }
        public Nullable<short> PCS { get; set; }
        public Nullable<short> DutyAfloatID { get; set; }
        public string OrderSubTypeID { get; set; }
        public string OrderTypeID { get; set; }
        public Nullable<int> DutyInfoID { get; set; }
        public Nullable<int> MissionID { get; set; }
        public string MissionName { get; set; }
        public Nullable<System.DateTime> MissionReportDate { get; set; }
        public Nullable<System.DateTime> MissionEndDate { get; set; }
        public Nullable<int> ReportingInfoID { get; set; }
        public string UIC { get; set; }
        public string UICName { get; set; }
        public Nullable<short> ConusOconusID { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public int ID { get; set; }
        public string RequirementName { get; set; }
        public string OperationExerciseEventID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> TotalDays { get; set; }
        public Nullable<short> RequirementStateID { get; set; }
        public string Comments { get; set; }
        public Nullable<short> NumberofOfficers { get; set; }
        public Nullable<short> NumberofEnlisted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string PocOrganization { get; set; }
        public string PocEmail { get; set; }
        public string PocPhone { get; set; }
        public string PocName { get; set; }
        public Nullable<int> RequirementOwnerID { get; set; }
        public string ConOcon { get; set; }
        public string ClearanceType { get; set; }
        public string OpEvEx { get; set; }
        public string ReqState { get; set; }
        public string OrdType { get; set; }
        public string OrdSubType { get; set; }
        public Nullable<short> NROWSIDAvailable { get; set; }
        public string NROWSRequirementID { get; set; }
        public string Source { get; set; }
        public string RankSwitch { get; set; }
    }
}
