//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditGetRequirement
    {
        public int AuditID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string Designator { get; set; }
        public string Rating { get; set; }
        public string NOBC { get; set; }
        public string NEC { get; set; }
        public string MissionName { get; set; }
        public string RequirementName { get; set; }
        public string AdvertisementID { get; set; }
        public string OrderType { get; set; }
        public string RankSwitch { get; set; }
    }
}
