//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DD_View
    {
        public int REQUIREMENT_ID { get; set; }
        public Nullable<int> MISSION_ID { get; set; }
        public string REQUIREMENT_NAME { get; set; }
        public Nullable<byte> REQUIREMENT_STATE { get; set; }
        public Nullable<short> FILL_MODE { get; set; }
        public Nullable<short> NUMBER_ENLISTED { get; set; }
        public Nullable<short> NUMBER_OFFICERS { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> TOTAL_DAYS { get; set; }
        public string UIC { get; set; }
        public string UIC_NAME { get; set; }
        public string DUTY_CITY { get; set; }
        public string DUTY_STATE { get; set; }
        public string DUTY_ZIP_CODE { get; set; }
        public string DUTY_COUNTRY { get; set; }
        public string POC_NAME { get; set; }
        public string POC_PHONE { get; set; }
        public string POC_EMAIL { get; set; }
        public string OPERATION_EXERCISE_EVENT_ID { get; set; }
        public string ORDER_TYPE_CODE { get; set; }
        public string ORDER_SUBTYPE_CODE { get; set; }
        public Nullable<byte> DUTY_ABOARD_SHIP_IND { get; set; }
        public Nullable<byte> PCS_IND { get; set; }
        public string MINIMUM_RANK { get; set; }
        public string MAXIMUM_RANK { get; set; }
        public string DESIGNATOR { get; set; }
        public string RATE_RANK { get; set; }
        public string NOBC { get; set; }
        public string NEC { get; set; }
        public string AQD { get; set; }
        public string QUALIFICATIONS { get; set; }
        public string GENDER { get; set; }
        public Nullable<byte> SECURITY_CLEARANCE_REQUIRED { get; set; }
        public string SECURITY_CLEARANCE_TYPE { get; set; }
        public Nullable<byte> CONUS_OCONUS_IND { get; set; }
        public string SOURCE { get; set; }
    }
}
