//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutyInfo
    {
        public int DutyInfoID { get; set; }
        public string OrderTypeID { get; set; }
        public string OrderSubTypeID { get; set; }
        public Nullable<short> DutyAfloatID { get; set; }
        public Nullable<short> PCS { get; set; }
        public Nullable<int> RequirementInfoID { get; set; }
    
        public virtual YesNo YesNo { get; set; }
        public virtual OrderSubType OrderSubType { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual YesNo YesNo1 { get; set; }
        public virtual RequirementInfo RequirementInfo { get; set; }
    }
}
