//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NROWS_AD_LK_ADSW_AT_TYPES
    {
        public short LK_ADSW_ID { get; set; }
        public string ADSW_TYPE_CODE { get; set; }
        public string ADSW_DESCRIPTION { get; set; }
        public string ADSW_SHORT_DESCRIPTION { get; set; }
        public Nullable<byte> STATUS_CODE { get; set; }
    }
}
