//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NROWS_AD_MISSION
    {
        public int MISSION_ID { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string POC_NAME { get; set; }
        public string POC_EMAIL { get; set; }
        public string POC_PHONE { get; set; }
        public string POC_ORGANIZATION { get; set; }
        public string MISSION_COMMENTS { get; set; }
        public string MISSION_NAME { get; set; }
    }
}
