//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NROWS_AD_LK_ORDER_TYPE
    {
        public string ORDER_TYPE_CODE { get; set; }
        public string ORDER_TYPE { get; set; }
        public string SHORT_DESCRIPTION { get; set; }
    }
}
