//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NROWS_AD_LK_TYPE_SECURITY
    {
        public string SECURITY_ID { get; set; }
        public string TYPE_OF_CLEARANCE { get; set; }
    }
}
