//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NROWS_AD_FLEET_EXERCISE
    {
        public string FLEET_EXERCISE_CODE { get; set; }
        public string FLEET_EXERCISE_DESCRIPTION { get; set; }
        public Nullable<byte> STATUS_CODE { get; set; }
        public string USER_ID { get; set; }
        public string CHANGE_COMMENT { get; set; }
    }
}
