//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportingInfo
    {
        public int ReportingInfoID { get; set; }
        public string UIC { get; set; }
        public string UICName { get; set; }
        public Nullable<short> ConusOconusID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public Nullable<int> RequirementInfoID { get; set; }
    
        public virtual ConusOconu ConusOconu { get; set; }
        public virtual RequirementInfo RequirementInfo { get; set; }
    }
}
