//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementInfo
    {
        public RequirementInfo()
        {
            this.CandidateInfoes = new HashSet<CandidateInfo>();
            this.DutyInfoes = new HashSet<DutyInfo>();
            this.MissionInfoes = new HashSet<MissionInfo>();
            this.ReportingInfoes = new HashSet<ReportingInfo>();
            this.RequirementOwners = new HashSet<RequirementOwner>();
        }
    
        public int ID { get; set; }
        public string Source { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string AdvertisementID { get; set; }
        public string RequirementName { get; set; }
        public string OperationExerciseEventID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> TotalDays { get; set; }
        public Nullable<short> RequirementStateID { get; set; }
        public Nullable<short> NumberofEnlisted { get; set; }
        public Nullable<short> NumberofOfficers { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> MissionID { get; set; }
        public Nullable<short> NROWSIDAvailable { get; set; }
        public string NROWSRequirementID { get; set; }
    
        public virtual ICollection<CandidateInfo> CandidateInfoes { get; set; }
        public virtual ICollection<DutyInfo> DutyInfoes { get; set; }
        public virtual ICollection<MissionInfo> MissionInfoes { get; set; }
        public virtual ICollection<ReportingInfo> ReportingInfoes { get; set; }
        public virtual ICollection<RequirementOwner> RequirementOwners { get; set; }
    }
}
