//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2S.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YesNo
    {
        public YesNo()
        {
            this.CandidateInfoes = new HashSet<CandidateInfo>();
            this.DutyInfoes = new HashSet<DutyInfo>();
            this.DutyInfoes1 = new HashSet<DutyInfo>();
        }
    
        public short Value { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CandidateInfo> CandidateInfoes { get; set; }
        public virtual ICollection<DutyInfo> DutyInfoes { get; set; }
        public virtual ICollection<DutyInfo> DutyInfoes1 { get; set; }
    }
}
